/**
 * Visual Feedback Loop Type Definitions
 *
 * Core types for the AI-verified design generation system with
 * multi-candidate generation and tiered verification.
 */

// =============================================================================
// Design Intent
// =============================================================================

/**
 * Parsed user intent for design generation
 */
export interface DesignIntent {
  /** Original user prompt */
  description: string;
  /** Extracted design constraints */
  constraints?: DesignConstraint[];
  /** Reference images provided by user */
  references?: ReferenceImage[];
  /** Style preferences */
  style?: StylePreferences;
  /** Parsed requirements */
  requirements?: ParsedRequirements;
}

export interface DesignConstraint {
  type: 'size' | 'color' | 'layout' | 'content' | 'style' | 'accessibility';
  description: string;
  priority: 'required' | 'preferred' | 'optional';
}

export interface ReferenceImage {
  data: string; // base64
  mediaType: 'image/png' | 'image/jpeg' | 'image/webp';
  description?: string;
}

export interface StylePreferences {
  colorScheme?: 'light' | 'dark' | 'auto';
  primaryColor?: string;
  style?: 'minimal' | 'modern' | 'classic' | 'playful' | 'corporate';
  density?: 'compact' | 'comfortable' | 'spacious';
}

export interface ParsedRequirements {
  elements: string[];
  layout?: string;
  interactions?: string[];
  responsive?: boolean;
}

// =============================================================================
// Design Candidates
// =============================================================================

/**
 * Generation strategy used to create a candidate
 */
export type GenerationStrategy =
  | 'initial'      // First generation from intent
  | 'refinement'   // Improve based on critique
  | 'crossover'    // Combine elements from multiple candidates
  | 'mutation'     // Random variations
  | 'fresh'        // Generate new from scratch
  | 'diversity';   // Deliberately different

/**
 * A design candidate generated by the AI
 */
export interface DesignCandidate {
  /** Unique identifier */
  id: string;
  /** Serialized design state (tool calls or scene snapshot) */
  seed: string;
  /** How this candidate was generated */
  generationMethod: GenerationStrategy;
  /** Parent candidate ID (for refinement/mutation) */
  parentId?: string;
  /** Parent IDs (for crossover) */
  parentIds?: string[];
  /** Iteration when this candidate was created */
  iterationBorn: number;
  /** Additional metadata */
  metadata: CandidateMetadata;
}

export interface CandidateMetadata {
  /** Temperature used for generation */
  temperature?: number;
  /** Refinement focus area */
  refinementFocus?: string;
  /** Confidence in improvement */
  improvementConfidence?: number;
  /** Parent scores (for crossover) */
  parentScores?: number[];
  /** Generation timestamp */
  generatedAt: number;
}

/**
 * A candidate after rendering
 */
export interface RenderedCandidate {
  /** The original candidate */
  candidate: DesignCandidate;
  /** Screenshot data */
  screenshot: ScreenshotData | null;
  /** Whether rendering succeeded */
  renderSuccessful: boolean;
  /** Error message if render failed */
  error?: string;
  /** Render timing */
  renderTimeMs?: number;
}

export interface ScreenshotData {
  /** Full resolution screenshot (base64 PNG) */
  full: string;
  /** Thumbnail for quick display (base64 PNG) */
  thumbnail: string;
  /** Screenshot dimensions */
  dimensions: {
    width: number;
    height: number;
  };
  /** Device pixel ratio used */
  devicePixelRatio: number;
}

// =============================================================================
// Verification
// =============================================================================

/**
 * Verification tier selection
 */
export type VerificationTier = 'standard' | 'advanced';

/**
 * Available verification models
 */
export type VerificationModelName = 'claude' | 'openai' | 'ollama';

/**
 * Configuration for verification
 */
export interface VerificationConfig {
  /** Which tier to use */
  tier: VerificationTier;
  /** Standard tier: which single model to use */
  primaryModel?: VerificationModelName;
  /** Advanced tier: multi-model configuration */
  advancedConfig?: AdvancedVerificationConfig;
}

export interface AdvancedVerificationConfig {
  /** Models to use with their weights */
  models: VerificationModelConfig[];
  /** Minimum consensus required (0-1) */
  consensusThreshold: number;
}

export interface VerificationModelConfig {
  name: VerificationModelName;
  weight: number;
  enabled: boolean;
}

/**
 * Result from a single verification model
 */
export interface ModelVerificationResult {
  /** Overall score (0-1) */
  score: number;
  /** Model's confidence in its assessment (0-1) */
  confidence: number;
  /** Critique text */
  critique: string;
  /** Category-specific scores */
  categories: VerificationCategories;
  /** Raw response for debugging */
  rawResponse?: string;
}

export interface VerificationCategories {
  /** Layout correctness (0-1) */
  layout: number;
  /** Visual fidelity to intent (0-1) */
  fidelity: number;
  /** Completeness of elements (0-1) */
  completeness: number;
  /** Polish and refinement (0-1) */
  polish: number;
}

/**
 * Fused verification result from one or more models
 */
export interface VerificationResult {
  /** Overall score (0-1) */
  overallScore: number;
  /** Whether the design is acceptable */
  acceptable: boolean;
  /** Combined critique */
  critique: string;
  /** Detailed analysis by category */
  detailedAnalysis: DetailedAnalysis;
  /** Agreement between models (1.0 for single model) */
  modelConsensus: number;
  /** Overall confidence */
  confidence: number;
  /** Which tier was used */
  verificationTier: VerificationTier;
  /** Breakdown by model (Advanced tier only) */
  modelBreakdown?: ModelScore[];
}

export interface DetailedAnalysis {
  categories: VerificationCategories;
  issues: DesignIssue[];
  strengths: string[];
  suggestions: string[];
}

export interface DesignIssue {
  type: 'layout' | 'color' | 'typography' | 'spacing' | 'alignment' | 'missing' | 'extra' | 'accessibility';
  severity: 'critical' | 'major' | 'minor';
  description: string;
  location?: string;
  suggestion?: string;
}

export interface ModelScore {
  model: VerificationModelName;
  score: number;
  weight: number;
  confidence: number;
  critique: string;
}

// =============================================================================
// Quality Scoring
// =============================================================================

/**
 * Quality component names
 */
export type QualityComponentName =
  | 'visual_fidelity'
  | 'technical_correctness'
  | 'design_principles'
  | 'intent_alignment';

/**
 * A single quality component
 */
export interface QualityComponent {
  name: QualityComponentName;
  weight: number;
  score: number;
  confidence: number;
}

/**
 * Complete quality score for a candidate
 */
export interface QualityScore {
  /** Overall weighted score (0-1) */
  overall: number;
  /** Individual components */
  components: QualityComponent[];
  /** Overall confidence */
  confidence: number;
  /** Normalized score (0-100 for display) */
  normalizedScore: number;
  /** Estimated improvement potential (0-1) */
  improvementPotential: number;
}

/**
 * A fully scored candidate
 */
export interface ScoredCandidate {
  candidate: DesignCandidate;
  rendered: RenderedCandidate;
  verification: VerificationResult;
  qualityScore: QualityScore;
}

// =============================================================================
// Termination
// =============================================================================

/**
 * Termination strategy names
 */
export type TerminationStrategyName =
  | 'quality_threshold'
  | 'convergence_detection'
  | 'diminishing_returns'
  | 'timeout'
  | 'diversity_depletion';

/**
 * Decision from a single termination strategy
 */
export interface StrategyTerminationDecision {
  strategyName: TerminationStrategyName;
  terminate: boolean;
  confidence: number;
  reason?: string;
}

/**
 * Fused termination decision
 */
export interface TerminationDecision {
  shouldTerminate: boolean;
  reason?: string;
  confidence: number;
  strategyBreakdown: StrategyTerminationDecision[];
  alternativeSuggestions?: TerminationSuggestion[];
}

export interface TerminationSuggestion {
  type: 'change_strategy' | 'increase_diversity' | 'adjust_threshold' | 'continue';
  reason: string;
  action: string;
  confidence: number;
}

// =============================================================================
// Feedback Iteration
// =============================================================================

/**
 * Performance metrics for an iteration
 */
export interface PerformanceMetrics {
  /** Total iteration time (ms) */
  totalTimeMs: number;
  /** Time spent rendering (ms) */
  renderTimeMs: number;
  /** Time spent on verification (ms) */
  verificationTimeMs: number;
  /** Time spent generating candidates (ms) */
  generationTimeMs: number;
  /** Memory usage (bytes) */
  memoryUsage?: number;
  /** API calls made */
  apiCalls: number;
  /** Estimated cost (USD) */
  estimatedCost?: number;
}

/**
 * A single iteration of the feedback loop
 */
export interface FeedbackIteration {
  /** Iteration number (1-based) */
  iteration: number;
  /** Timestamp */
  timestamp: number;
  /** All candidates evaluated this iteration */
  candidates: ScoredCandidate[];
  /** Best candidate from this iteration */
  bestCandidate: ScoredCandidate;
  /** Termination check result */
  terminationCheck: TerminationDecision;
  /** Performance metrics */
  performanceMetrics: PerformanceMetrics;
  /** Strategies used for generation */
  strategiesUsed: GenerationStrategy[];
}

// =============================================================================
// Feedback Loop Options & Result
// =============================================================================

/**
 * Options for the feedback loop
 */
export interface FeedbackLoopOptions {
  /** Maximum iterations (default: 10) */
  maxIterations?: number;
  /** Quality threshold for acceptance (default: 0.85) */
  qualityThreshold?: number;
  /** Total timeout in ms (default: 60000) */
  timeoutMs?: number;
  /** Enable early stopping (default: true) */
  enableEarlyStopping?: boolean;
  /** Number of candidates per iteration (default: 3) */
  candidatesPerIteration?: number;
  /** Verification configuration */
  verification?: VerificationConfig;
  /** Progress callback */
  onProgress?: (iteration: FeedbackIteration) => void;
  /** Screenshot callback (for UI preview) */
  onScreenshot?: (screenshot: ScreenshotData, candidateId: string) => void;
}

/**
 * Final result from the feedback loop
 */
export interface DesignResult {
  /** Whether generation was successful */
  success: boolean;
  /** The final design candidate */
  finalCandidate: DesignCandidate;
  /** Final screenshot */
  finalScreenshot: ScreenshotData;
  /** Final quality score */
  qualityScore: QualityScore;
  /** All iterations */
  iterations: FeedbackIteration[];
  /** Total iterations used */
  totalIterations: number;
  /** Total time (ms) */
  totalTimeMs: number;
  /** Termination reason */
  terminationReason: string;
  /** Analytics data */
  analytics?: DesignAnalytics;
}

export interface DesignAnalytics {
  /** Score progression over iterations */
  scoreProgression: number[];
  /** Strategy effectiveness */
  strategyEffectiveness: Record<GenerationStrategy, number>;
  /** Average iteration time */
  avgIterationTimeMs: number;
  /** Total API cost estimate */
  totalCostEstimate: number;
  /** Convergence analysis */
  convergenceAnalysis: ConvergenceAnalysis;
}

export interface ConvergenceAnalysis {
  /** Whether scores converged */
  converged: boolean;
  /** Rate of convergence */
  convergenceRate: number;
  /** Whether oscillation was detected */
  oscillationDetected: boolean;
  /** Whether a plateau was detected */
  plateauDetected: boolean;
}

// =============================================================================
// Adaptive Configuration
// =============================================================================

/**
 * Adaptive configuration that changes based on performance
 */
export interface AdaptiveConfig {
  /** Exploration rate (0-1) */
  explorationRate: number;
  /** Current temperature */
  temperature: number;
  /** Minimum candidate diversity */
  minDiversity: number;
  /** Verification timeout (ms) */
  verificationTimeout: number;
  /** Whether to prefer local models */
  preferLocal: boolean;
}

/**
 * Temperature schedule for generation
 */
export interface TemperatureSchedule {
  /** Initial temperature */
  initial: number;
  /** Minimum temperature */
  min: number;
  /** Maximum temperature */
  max: number;
  /** Decay rate per iteration */
  decayRate: number;
}

// =============================================================================
// Utility Types
// =============================================================================

/**
 * Generate a unique ID
 */
export function generateId(): string {
  return `${Date.now()}_${Math.random().toString(36).slice(2, 11)}`;
}

/**
 * Default feedback loop options
 */
export const DEFAULT_FEEDBACK_OPTIONS: Required<Omit<FeedbackLoopOptions, 'onProgress' | 'onScreenshot'>> = {
  maxIterations: 10,
  qualityThreshold: 0.85,
  timeoutMs: 60000,
  enableEarlyStopping: true,
  candidatesPerIteration: 3,
  verification: {
    tier: 'standard',
    primaryModel: 'claude',
  },
};

/**
 * Default adaptive configuration
 */
export const DEFAULT_ADAPTIVE_CONFIG: AdaptiveConfig = {
  explorationRate: 0.3,
  temperature: 0.7,
  minDiversity: 0.2,
  verificationTimeout: 15000,
  preferLocal: false,
};

/**
 * Default temperature schedule
 */
export const DEFAULT_TEMPERATURE_SCHEDULE: TemperatureSchedule = {
  initial: 0.7,
  min: 0.3,
  max: 1.0,
  decayRate: 0.1,
};

/**
 * Quality component weights
 */
export const QUALITY_COMPONENT_WEIGHTS: Record<QualityComponentName, number> = {
  visual_fidelity: 0.4,
  technical_correctness: 0.2,
  design_principles: 0.2,
  intent_alignment: 0.2,
};
